export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userSignUpConstants = {
  USER_SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  USER_SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}

export const getCategoryConstants = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  ADD_CATEGORIES_REQUEST: 'ADD_CATEGORIES_REQUEST',
  ADD_CATEGORIES_SUCCESS: 'ADD_CATEGORIES_SUCCESS',
  ADD_CATEGORIES_FAILURE: 'ADD_CATEGORIES_FAILURE'
}
export const productConstants = {
  GET_PRODUCTS_BY_SLUG_REQUEST: 'GET_PRODUCTS_BY_SLUG_REQUEST',
  GET_PRODUCTS_BY_SLUG_SUCCESS: 'GET_PRODUCTS_BY_SLUG_SUCCESS',
  GET_PRODUCTS_BY_SLUG_FAILURE: 'GET_PRODUCTS_BY_SLUG_FAILURE',

  GET_PRODUCT_DETAILS_BY_ID_REQUEST: ' GET_PRODUCT_DETAILS_BY_ID_REQUEST',
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: ' GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: ' GET_PRODUCT_DETAILS_BY_ID_FAILURE',

  GET_PRODUCT_PAGE_TYPE_REQUEST: 'GET_PRODUCT_PAGE_TYPE_REQUEST',
  GET_PRODUCT_PAGE_TYPE_SUCCESS: 'GET_PRODUCT_PAGE_TYPE_SUCCESS',
  GET_PRODUCT_PAGE_TYPE_FAILURE: 'GET_PRODUCT_PAGE_TYPE_FAILURE'
}

export const cartConstants = {
  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

  GET_CART_ITEMS_REQUEST: 'GET_CART_ITEMS_REQUEST',
  GET_CART_ITEMS_SUCCESS: 'GET_CART_ITEMS_SUCCESS',
  GET_CART_ITEMS_FAILURE: 'GET_CART_ITEMS_FAILURE',

  REMOVE_CART_ITEM_REQUEST: 'REMOVE_CART_ITEM_REQUEST',
  REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
  REMOVE_CART_ITEM_FAILURE: 'REMOVE_CART_ITEM_FAILURE',
  RESET_CART: 'RESET_CART'
}
export const userConstants = {
  GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
  GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
  GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',

  ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
  ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
  ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',

  ADD_USER_ORDER_REQUEST: 'ADD_USER_ORDER_REQUEST',
  ADD_USER_ORDER_SUCCESS: 'ADD_USER_ORDER_SUCCESS',
  ADD_USER_ORDER_FAILURE: 'ADD_USER_ORDER_FAILURE',

  GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST',
  GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS',
  GET_USER_ORDER_FAILURE: 'GET_USER_ORDER_FAILURE',

  GET_USER_ORDER_DETAILS_REQUEST: 'GET_USER_ORDER_DETAILS_REQUEST',
  GET_USER_ORDER_DETAILS_SUCCESS: 'GET_USER_ORDER_DETAILS_SUCCESS',
  GET_USER_ORDER_DETAILS_FAILURE: 'GET_USER_ORDER_DETAILS_FAILURE'
}

// export const initialDataConstant = {
//   GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
//   GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
//   GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
// }
